# Основные настройки сервера
server_names = ['comss']
listen_addresses = ['127.0.0.1:5354']
max_clients = 250

# Настройки протоколов DNS
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
odoh_servers = false

# Требования к серверам DNS
require_dnssec = true
require_nolog = true
require_nofilter = true

# Прочие настройки
force_tcp = false
http3 = false
timeout = 2500
keepalive = 0
blocked_query_response = 'refused'
cert_refresh_delay = 240  # Обновление сертификатов каждые 4 часа
dnscrypt_ephemeral_keys = true  # Использование эфемерных ключей для увеличения безопасности

# Конфигурация кэша
cache = true
cache_size = 4096
cache_min_ttl = 60
cache_max_ttl = 600
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

# Блокировки
block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 10

# Настройки Bootstrap DNS
bootstrap_resolvers = ['1.1.1.1:53', '8.8.8.8:53']
ignore_system_dns = true
netprobe_timeout = 30
netprobe_address = '1.1.1.1:53'

# Логирование
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
blocked_names_file = 'blocked-names.txt'
blocked_ips_file = 'blocked-ips.txt'
allowed_names_file = 'allowed-names.txt'
allowed_ips_file = 'allowed-ips.txt'

# Источники DNS серверов
[sources.public-resolvers]
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
cache_file = 'public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 24

[sources.relays]
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md']
cache_file = 'relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 24

# Обход ограничений на обработку фрагментов для некоторых серверов
fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'cleanbrowsing-adult', 'cleanbrowsing-adult-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-security', 'cleanbrowsing-security-ipv6']

# Анонимизированный DNS
[anonymized_dns]
routes = [
    { server_name='ams-dnscrypt-nl', via=['anon-meganerd', 'anon-scaleway-ams'] },
    { server_name='d0wn-tz-ns1', via=['anon-arapurayil-in-ipv4', 'anon-cs-rome'] }
]
skip_incompatible = true
direct_cert_fallback = false

# Статические записи серверов
[static]
[static.'comss']
stamp = 'sdns://AgcAAAAAAAAAAAAQZG5zLmNvbnRyb2xkLmNvbQYvY29tc3M'
