
##############################################
#                                            #
#        dnscrypt-proxy configuration        #
#                                            #
##############################################

server_names = ['comss']
listen_addresses = ['127.0.0.1:5354']
max_clients = 50

## Require servers (from remote sources) to satisfy specific properties

ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = false
doh_servers = true
odoh_servers = false

## Require servers defined by remote sources to satisfy specific properties

require_dnssec = false
require_nolog = true
require_nofilter = false
disabled_server_names = []

## Always use TCP to connect to upstream servers.

force_tcp = false

## Enable *experimental* support for HTTP/3 (DoH3, HTTP over QUIC)

http3 = false

## How long a DNS query will wait for a response, in milliseconds.

timeout = 1000
keepalive = 20

## Response for blocked queries.

blocked_query_response = 'refused'

## Delay, in minutes, after which certificates are reloaded

cert_refresh_delay = 240

## DNSCrypt: Create a new, unique key for every single DNS query

dnscrypt_ephemeral_keys = true

## Bootstrap resolvers

bootstrap_resolvers = ['9.9.9.9:53', '1.1.1.1:53']
ignore_system_dns = true

## Maximum time (in seconds) to wait for network connectivity before
## initializing the proxy.

netprobe_timeout = 60
netprobe_address = '8.8.4.4:53'

## Automatic log files rotation

log_files_max_size = 1
log_files_max_age = 3
log_files_max_backups = 0

#########################
#        Filters        #
#########################

block_ipv6 = true
block_unqualified = true
block_undelegated = true
reject_ttl = 10

###########################
#        DNS cache        #
###########################

cache = true
cache_size = 1024
cache_min_ttl = 600
cache_max_ttl = 7200
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

######################################################
#        Pattern-based blocking (blocklists)         #
######################################################

[blocked_names]

blocked_names_file = 'blocked-names.txt'

###########################################################
#        Pattern-based IP blocking (IP blocklists)        #
###########################################################

[blocked_ips]

blocked_ips_file = 'blocked-ips.txt'

######################################################
#   Pattern-based allow lists (blocklists bypass)    #
######################################################

[allowed_names]

allowed_names_file = 'allowed-names.txt'

#########################################################
#   Pattern-based allowed IPs lists (blocklists bypass) #
#########################################################

[allowed_ips]

allowed_ips_file = 'allowed-ips.txt'

#########################
#        Servers        #
#########################

[sources]

  [sources.public-resolvers]
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md']
    cache_file = 'public-resolvers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''

  [sources.relays]
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md']
    cache_file = 'relays.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 72
    prefix = ''

########################################
#            Static entries            #
########################################

[static]

[static.'comss']
stamp = 'sdns://AgcAAAAAAAAAAAAQZG5zLmNvbnRyb2xkLmNvbQYvY29tc3M'
